version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0

    working_directory: ~/app

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - birthdates_api-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - birthdates_api-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: birthdates_api-{{ checksum "package.json" }}
        
      # run lint!
      - run: npm run lint
  deploy:
        docker:
          - image: circleci/node:8.10.0

        working_directory: ~/app

        steps:
          - checkout
          - run:
              name: Install Heroku
              command: bash .circleci/install_heroku.sh
          - run:
              name: Deploy master to Heroku
              command: |  # this command is framework-dependent and may vary
                heroku git:remote -a $HEROKU_APP_NAME
                git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:refs/heads/master
                sleep 5  # sleep for 5 seconds to wait for dynos
                heroku restart

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:  # only deploy when master successfully builds
          requires:
            - build
          filters:
            branches:
              only: master